web:
  isProdEnv: false
  title: "gin_template"
  description: "gin 模板"
  addr: "0.0.0.0:8080"
  secretKey: "xxxxxxxx"
  version: "v1.0"
  apiPrefixPath: "/api"

mongoDB:
  url: "127.0.0.1:27017"
  username: "test"
  password: "test"
  defaultDb: "admin"

gaussDB:
  host: "127.0.0.1"
  port: 5432
  user: "ytx"
  password: "Gaussdb@1"
  dbName: "postgres"
  sslmode: "disable"
